### ISSUE TITLE
Migrate / Fork / Re-fork this repo to the Isobar Github user account.

### ISSUE THREAD

**Issue by rcherny** [isobar-us/code-standards#28]
We have a new Isobar-proper account that we will be using in the (hopefully) near future.

Possibly we for this over there, remove this, and re-fork back here ... so people can find it.

Open to suggestions.

**Comment by rcherny** [comment]
Closing this because the whole repo has been moved.

**Comment by roblarsen** [comment]
Hi @rcherny !

**Comment by amcintyre-cs** [comment]
I’M HERE, TOO!

**Comment by candrews** [comment]
Me three! 👋

**Comment by rcherny** [comment]
Hahaha Hey guys!

(Really need to clean up this board)

I do wonder ... If the standards were actually re-written for 2021, what would they look like? 

Hmmm... 🤔💭

**Comment by roblarsen** [comment]
They would be 10000000 pages long
